server:
  port: 80

spring:
  application:
    name: kp-freetraffic
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dell-/v0Q61f0
    url: jdbc:mysql://139.196.180.61:3306/kp_freetraffic_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-test-query: select 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

swagger:
  enabled: true

cmcc:
  url:
    valid_token: http://120.197.235.102/api/uniTokenValidate/
    login: http://120.197.235.102/yzapi/api/login
    send_sms_code: http://120.197.235.102/yzapi/api/sendSmsCode
    add_order: https://sandbox.open.10086.cn/38857911/gateway/api/common/activity/order/addOrder
    query_order_result: https://sandbox.open.10086.cn/38857911/gateway/api/common/activity/order/fullfillmentResultQueryV2
  auth:
    sourceId: 001326
    sourceKey: n3uelzFYwsvyZHcs
    appId: 001326
    appKey: n3uelzFYwsvyZHcs
    userip: 139.196.180.61
  order:
    activityId: 123456789
    sourceApp: cmicCloudPhone
    sourceGoodsId: xxxxxx