server:
  port: 8081

cmcc_url:
  valid_token: http://120.197.235.102/api/uniTokenValidate/
  login: http://120.197.235.102/yzapi/api/login
  send_sms_code: http://120.197.235.102/yzapi/api/sendSmsCode
  add_order: https://sandbox.open.10086.cn/38857911/gateway/api/common/activity/order/addOrder
  query_order_result: https://sandbox.open.10086.cn/38857911/gateway/api/common/activity/order/fullfillmentResultQueryV2
